### ISSUE TITLE
Prevent creating two accounts with @gmail.com and @googlemail.com

### ISSUE THREAD

**Issue by IchordeDionysos** [firebase/FirebaseUI-iOS#802] opened 2019-11-14 22:12 UTC
I know this is a very specific use-case and this will probably not be integrated directly into Firebase Authentication.
So my second guess was, Firebase UI is to provide the best user experience for authentication.
And we regularly see a problem where users complain that they logged in again and don't have access to their subscriptions anymore and this only because the logged in with the other Gmail domain and so they create a new account instead of just logging in.

#### Steps to reproduce:

  1. Create an account with example@googlemail.com
  2. Logout
  3. Create an account with example@gmail.com
  
#### Observed Results:

  * There will be two accounts created for example@googlemail.com and example@gmail.com
  
#### Expected Results:

  * The user should have been informed that there is already an account with @googlemail.com and asked if he wants to log in to this account instead.

**Comment by morganchen12** [comment] 2019-11-14 22:24
This is intended behavior. Note that you can also create an account with `example+firebaseui@gmail.com`. Those may be distinct accounts that belong to the same individual and I'm not convinced it's the right thing for the auth provider to force those two accounts to be the same account.

**Comment by IchordeDionysos** [comment] 2019-11-15 10:21
I understand that this is intended and I highly expected that :)
I also know that you can use `example+firebaseui@gmail.com`, in this case, if the user EXPLICITLY wants separate accounts, let him.

I also would not force the user to use EITHER @gmail.com or @googlemail.com, I would check if he already has created an account with either of those emails and give the user the CHOICE.

The majority of our users are simply not aware of the fact that they created TWO accounts and giving them a hint before creating the second account I believe might be the right choice.

This is what we would envision the feature to look like (I just quickly changed the HTML :D): 
![image](https://user-images.githubusercontent.com/10195482/68935989-d13c4480-0799-11ea-9e17-8309aba2d401.png)
![image](https://user-images.githubusercontent.com/10195482/68936002-d600f880-0799-11ea-98f1-0d0fe35f4eb3.png)
![image](https://user-images.githubusercontent.com/10195482/68936009-d8fbe900-0799-11ea-8d4a-d3a3e1ee6765.png)

Again we would not force anybody to use anything, we would just inform users who might not think that there is a difference or might not know they used @googlemail.com the last time.
Also, we could make this an optional feature of Firebase UI so not every developer will have to use it.

**Comment by morganchen12** [comment] 2019-11-15 18:39
It's something we could do in FirebaseUI. I'll leave this feature request open to see if there's interest from other users as well.

**Comment by morganchen12** [comment] 2020-01-06 22:48
Closing this since it doesn't seem to have collected any other interest.

**Closed by morganchen12** 2020-01-06 22:48 UTC
Labels: type: feature request
