### ISSUE TITLE
"Unsupported use of UIKit API off the main thread" still happening

### ISSUE THREAD

**Issue by nissaba** [firebase/FirebaseUI-iOS#826] opened 2020-01-10 18:56 UTC
* Xcode version: Version 11.3 (11C29)
  * Firebase SDK version: deepens on component, not using the full sdk
  * Firebase Component: FirebaseAnalytics, FirebaseUI/Auth, FirebaseUI/Email, Crashlytics( ~> 3.12.0), FirebasePerformance( ~> 2.2), Firebase/Core

  * Component version: * see above. this is installed via cocoaPods

Description: 
The console log are showing many very invasive and frequent logs...
2020-01-10 13:42:26.428211-0500 notio[6974:2438880] [Assert] Unsupported use of UIKit API off the main thread: UIAccessibilityIsGuidedAccessEnabled()
2020-01-10 13:42:26.431560-0500 notio[6974:2438880] [Assert] Unsupported use of UIKit API off the main thread: UIAccessibilityIsAssistiveTouchRunning()

 Steps to reproduce:
Install the cocoaPods component and use them. Un able to pinpoint why this is happening

The problem is as said previously, extremely invasive logs that are making debugging difficult to read. 

2020-01-10 13:42:26.428211-0500 notio[6974:2438880] [Assert] Unsupported use of UIKit API off the main thread: UIAccessibilityIsGuidedAccessEnabled()
2020-01-10 13:42:26.431560-0500 notio[6974:2438880] [Assert] Unsupported use of UIKit API off the main thread: UIAccessibilityIsAssistiveTouchRunning()

pod installation 

platform :ios, '11.0'
target 'MyAppThing' do
  use_frameworks!
  pod 'SwiftLint'
  pod 'Firebase/Core'
  pod 'FirebaseAnalytics'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Email'
  pod 'Crashlytics', '~> 3.12.0'
  pod 'FirebasePerformance', '~> 2.2'
  pod 'iOSDFULibrary'
end

**Comment by morganchen12** [comment] 2020-01-21 19:50
@nissaba can you upload a sample project that reproduces your build error? The FirebaseUI samples build without issue.

**Comment by nissaba** [comment] 2020-01-21 21:39
I trier to make a small sample. but I am not able to reproduce this. The project I am working on is dating back a bit and this is leading me to think this could be some obscure project settings that CocoaPods do not like. I really hop to be able at some point to use Swiftpackage manager instead

**Comment by morganchen12** [comment] 2020-01-21 22:39
The error is likely somewhere in your build flags. You can try comparing the build flags of the new project that doesn't reproduce the error to the flags in your old project.

I'm going to close this issue since it doesn't seem to be a Firebase/FirebaseUI issue anymore, but feel free to continue commenting if you need more help.

**Closed by morganchen12** 2020-01-21 22:39 UTC
