### ISSUE TITLE
Pod Install not working

### ISSUE THREAD

**Issue by anilios** [firebase/FirebaseUI-iOS#285] opened 2017-06-01 11:12 UTC
I was trying to run and see Phone Authentication sample UI for iOS using xcode8.3. But when I tried to run pod install command as mention in the README.md instructions,   I am getting following error:

`FirebaseUI-iOS rajendersha$ pod install
Analyzing dependencies
Fetching podspec for `FirebaseAuthUI` from `FirebaseUI_dev_auth.podspec`
Fetching podspec for `FirebaseDatabaseUI` from `FirebaseUI_dev_db.podspec`
Fetching podspec for `FirebaseFacebookAuthUI` from `FirebaseUI_dev_fb.podspec`
Fetching podspec for `FirebaseGoogleAuthUI` from `FirebaseUI_dev_ggl.podspec`
Fetching podspec for `FirebasePhoneAuthUI` from `FirebaseUI_dev_phone.podspec`
Fetching podspec for `FirebaseStorageUI` from `FirebaseUI_dev_storage.podspec`
Fetching podspec for `FirebaseTwitterAuthUI` from `FirebaseUI_dev_tw.podspec`
[!] Unable to find host target(s) for Database, Storage, Auth, Facebook, Google, Phone, Twitter. Please add the host targets for the embedded targets to the Podfile.
Certain kinds of targets require a host target. A host target is a "parent" target which embeds a "child" target. These are example types of targets that need a host target:
- Framework
- App Extension
- Watch OS 1 Extension
- Messages Extension (except when used with a Messages Application)`

However I am able to run swift sample after running pod install command, but I can not see any option for Phone Authentication UI in the sample app.

**Comment by morganchen12** [comment] 2017-06-01 17:14
Duplicate of #283

**Closed by morganchen12** 2017-06-01 17:14 UTC

**Comment by anilios** [comment] 2017-06-02 07:11
Ok thanks, I am able to fix this issue.
