### ISSUE TITLE
call to displayName after Email signup is returning Nil 

### ISSUE THREAD

**Issue by vamshire** [firebase/FirebaseUI-iOS#262] opened 2017-03-14 04:46 UTC
Using swift. 
iOS version 10.2. 
Firebase SDK version: 3.14.0
FirebaseUI version: 2.0.0
CocoaPods Version: 1.2
  
I have enabled FB and login by email. Email logins created just fine. UI asks for Display Name but is not returning the display name when I try to get it with FIRAuth.auth()?.currentUser?.displayName

I'm expecting the displayName collected from the UI to be returned.

**Comment by yramanchuk** [comment] 2017-03-28 21:01
@vamshire I can't reproduce the issue. Can you please:
- double-check issue with the latest version of FirebaseUI;
- try different FB account;
- verify `FIRUser` from `FIRAuthStateDidChangeListenerHandle`.

**Comment by morganchen12** [comment] 2017-04-19 23:26
Closing due to inactivity, @vamshire feel free to reopen this issue if it's still relevant.

**Comment by FredvanRijswijk** [comment] 2017-05-29 08:53
Also with the latest SDK this is relevant:

the user object is returning this:
`{ email: 'testtttting@at.com',
  metadata: 
   { createdAt: 2017-05-29T08:23:44.000Z,
     lastSignedInAt: 2017-05-29T08:23:44.000Z },
  uid: 'Rw6XI2uhQXEn5yzdchvhbXI42' }`

displayName is not set directly after signup?

**Comment by murjax** [comment] 2017-10-12 21:21
Can we reopen this issue? I'm having the same problem. When I call `displayName` on the Firebase user after sign up, it is null despite me providing one. Email is present so I don't understand why displayName is not. Thanks.

**Comment by morganchen12** [comment] 2018-01-10 22:46
Closing this, as it has staled. If you still have this issue, please file it over at the main Firebase iOS repo.

**Closed by morganchen12** 2018-01-10 22:46 UTC
Labels: feature:auth

**Comment by manmanmaaaaan** [comment] 2018-04-25 18:06
still having this issue in swift 4. very easy to reproduce for me 

Auth.auth().signIn(withEmail: email, password: pass)
{ (user, error) in
         
  if let u = user
  {
    print("my display name is \(u.displayName) ")
  }
})

**Comment by morganchen12** [comment] 2018-04-26 18:25
This sounds like an upstream FirebaseAuth issue. @manmanmaaaaan what versions of Firebase/FirebaseUI are you using?

**Comment by manmanmaaaaan** [comment] 2018-04-26 21:30
thnx.I am using FireBaseAuth 4.6.1I have swift 4 and xcode 9.3Auth.auth().signIn(withEmail: $email, $password: pass){ (user, error) in                   if let e = error  {    let t = text_from_error_code(e._code)    alert(t, msg: e.localizedDescription, done:nil)  }  else if let u = user  {    print("name is \(u.displayName)")  }  else  {     alert("Hmm", msg:"No error, but could not log you in.", done:nil)  }





p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Menlo; color: #000000; background-color: #ffffff}
p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px Menlo; color: #d12f1b; background-color: #ffffff}
span.s1 {color: #ba2da2}
span.s2 {color: #000000}



















})I am seeing under my admin panel, in cloud firestore database under the 'users' collection, my name under the field 'displayName'


-------- Original Message --------
Subject: Re: [firebase/FirebaseUI-iOS] call to displayName after Email
signup is returning Nil (#262)

**Comment by manmanmaaaaan** [comment] 2018-04-26 21:34
under firebase 'Authentication' (not database) - I do find my user, but there is no way to set displayName, if I am supposed to set displayName there?? instead of under database, with collection 'users' ?

**Comment by radvansky-tomas** [comment] 2018-07-18 03:00
Any update on this ? FirebaseUI email provider is creating user without name, even though its part of the wizard.

**Comment by morganchen12** [comment] 2018-07-18 17:34
@radvansky-tomas what versions of Firebase/FirebaseUI are you using?

**Comment by morganchen12** [comment] 2018-12-18 17:38
@dmsl1805 are you using a provider with a display name?

**Comment by dmsl1805** [comment] 2018-12-19 07:50
> @dmsl1805 are you using a provider with a display name?

I try to get a name from either `Auth.auth().currentUser` or `user` instance inside `Auth.auth().addStateDidChangeListener` listener block.

Also I check `providerData` set from user and `displayName` in `FIRUserInfo` was also nil.

Here is and example of how I use it:
`
FUIAuth.defaultAuthUI()?.delegate = self
FUIAuth.defaultAuthUI()?.providers = [FUIGoogleAuth(), FUIFacebookAuth()]
let authSubscribtion = Auth.auth().addStateDidChangeListener { _, user in
  // Here user.displayName is nil, the same for Auth.auth().currentUser.displayName
}
`

**Comment by morganchen12** [comment] 2018-12-19 17:47
I see, that's a duplicate of #561.

**Comment by bdaz** [comment] 2019-04-17 02:48
FYI, this is not only a duplicate of #561. The original issue is correct: `displayName` on the user is nil in the `FIRAuthStateDidChangeListenerHandle` callback after creating an user via `FUIEmailAuth`.

The user is created just fine. In fact, sometime afterward `displayName` gets populated on the same `FIRUser` object (maybe after some kind of async networking).
