### ISSUE TITLE
FUIPasswordSignInViewController Not Dismissing

### ISSUE THREAD

**Issue by jessemx109** [firebase/FirebaseUI-iOS#419] opened 2018-03-12 22:18 UTC
### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 11
  * Firebase SDK version: 4.10.0
  * FirebaseUI version: 4.5.3
  * CocoaPods Version: 1.4.0
  
#### Steps to reproduce:

  1. Set FUIAuthPickerViewController as rootViewController of applications UIWindow
  2. Select email Sign in method
  3. Enter login information and press sign in button
  
#### Observed Results:

  View shows activity indicator, indicator goes away and app stay on sign in screen
  
#### Expected Results:

  View Should return control to the FUIAuthPickerViewController and call the method
```
authUI:(FUIAuth *)authUI
    didSignInWithUser:(nullable FIRUser *)user
                error:(nullable NSError *)error
```
  
#### Relevant Code:

  ```
  window.rootViewController = FUIAuth.defaultAuthUI()?.authViewController()
  ```
  The issue seems to be in FUIPasswordSignInViewController line 136 where the view calls dismissViewControllerAnimated which only works if the original FUIAuthPickerViewController was presented modally

**Comment by morganchen12** [comment] 2018-03-12 22:26
duplicate of #254

**Closed** 2018-03-12 22:27 UTC
