### ISSUE TITLE
xCode Build Error After last pods update

### ISSUE THREAD

**Issue by UtkuDalmaz** [firebase/FirebaseUI-iOS#379] opened 2017-12-20 02:01 UTC
I am having build errors after the last update of Firebase pods.

Xcode version 9.2

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_Twitter", referenced from:
      objc-class-ref in FirebaseTwitterAuthUI(FUITwitterAuth.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

How can I fix this problem?

<img width="1274" alt="screen shot 2017-12-20 at 04 15 27" src="https://user-images.githubusercontent.com/2130592/34187345-f8fc0fb8-e541-11e7-8ff4-09989733a04f.png">

**Comment by morganchen12** [comment] 2017-12-20 02:05
Duplicate of #378 

I can't debug this without at least your Podfile.lock

**Closed by morganchen12** 2017-12-20 02:05 UTC

**Comment by UtkuDalmaz** [comment] 2017-12-20 02:22
platform :ios, “10.0”

use_frameworks!

target “Jemiyet” do
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'TWMessageBarManager'
pod 'QMServices'
pod 'Fabric'
pod 'Crashlytics'
pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'ALCameraViewController'
pod 'Agrume'
pod 'SwiftyJSON'
pod 'ImageScrollView'
pod 'Alamofire'
pod 'FirebaseUI'
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/Performance'
pod 'PhoneNumberKit'
pod 'SCLAlertView', :git => 'https://github.com/vikmeup/SCLAlertView-Swift.git'
end

**Comment by morganchen12** [comment] 2017-12-20 02:35
That's your Podfile, not your Podfile.lock

**Comment by derekgould** [comment] 2018-01-01 20:03
I have the same issue. I can get around it by including only other FirebaseUI components (and leaving Twitter out), but if I include the complete FirebaseUI i get this error. Here's my podfile.lock.

PODS:
  - Bolts (1.9.0):
    - Bolts/AppLinks (= 1.9.0)
    - Bolts/Tasks (= 1.9.0)
  - Bolts/AppLinks (1.9.0):
    - Bolts/Tasks
  - Bolts/Tasks (1.9.0)
  - BoringSSL (9.1):
    - BoringSSL/Implementation (= 9.1)
    - BoringSSL/Interface (= 9.1)
  - BoringSSL/Implementation (9.1):
    - BoringSSL/Interface (= 9.1)
  - BoringSSL/Interface (9.1)
  - CDAlertView (0.7.0)
  - Eureka (4.0.1)
  - FBSDKCoreKit (4.29.0):
    - Bolts (~> 1.7)
  - FBSDKLoginKit (4.29.0):
    - FBSDKCoreKit
  - Firebase (4.8.0):
    - Firebase/Core (= 4.8.0)
  - Firebase/Auth (4.8.0):
    - Firebase/Core
    - FirebaseAuth (= 4.4.1)
  - Firebase/Core (4.8.0):
    - FirebaseAnalytics (= 4.0.5)
    - FirebaseCore (= 4.0.13)
  - Firebase/Database (4.8.0):
    - Firebase/Core
    - FirebaseDatabase (= 4.1.3)
  - Firebase/Firestore (4.8.0):
    - Firebase/Core
    - FirebaseFirestore (= 0.9.4)
  - Firebase/Storage (4.8.0):
    - Firebase/Core
    - FirebaseStorage (= 2.1.1)
  - FirebaseAnalytics (4.0.5):
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
    - nanopb (~> 0.3)
  - FirebaseAuth (4.4.1):
    - FirebaseAnalytics (~> 4.0)
    - GoogleToolboxForMac/NSDictionary+URLArguments (~> 2.1)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseCore (4.0.13):
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseDatabase (4.1.3):
    - FirebaseAnalytics (~> 4.0)
    - FirebaseCore (~> 4.0)
    - leveldb-library (~> 1.18)
  - FirebaseFirestore (0.9.4):
    - FirebaseAnalytics (~> 4.0)
    - FirebaseCore (~> 4.0)
    - gRPC-ProtoRPC (~> 1.0)
    - leveldb-library (~> 1.18)
    - Protobuf (~> 3.1)
  - FirebaseInstanceID (2.0.8):
    - FirebaseCore (~> 4.0)
  - FirebaseStorage (2.1.1):
    - FirebaseAnalytics (~> 4.0)
    - FirebaseCore (~> 4.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseUI (4.5.0):
    - FirebaseUI/All (= 4.5.0)
  - FirebaseUI/All (4.5.0):
    - FirebaseUI/Auth
    - FirebaseUI/Database
    - FirebaseUI/Facebook
    - FirebaseUI/Firestore
    - FirebaseUI/Google
    - FirebaseUI/Phone
    - FirebaseUI/Storage
    - FirebaseUI/Twitter
  - FirebaseUI/Auth (4.5.0):
    - Firebase/Auth (~> 4.2)
  - FirebaseUI/Database (4.5.0):
    - Firebase/Database (~> 4.0)
  - FirebaseUI/Facebook (4.5.0):
    - FBSDKLoginKit (~> 4.0)
    - FirebaseUI/Auth
  - FirebaseUI/Firestore (4.5.0):
    - Firebase/Firestore
  - FirebaseUI/Google (4.5.0):
    - FirebaseUI/Auth
    - GoogleSignIn (~> 4.0)
  - FirebaseUI/Phone (4.5.0):
    - FirebaseUI/Auth
  - FirebaseUI/Storage (4.5.0):
    - Firebase/Storage (~> 4.0)
    - SDWebImage (~> 4.0)
  - FirebaseUI/Twitter (4.5.0):
    - FirebaseUI/Auth
    - TwitterKit (~> 3.0)
  - GoogleSignIn (4.1.1):
    - GoogleToolboxForMac/NSDictionary+URLArguments (~> 2.1)
    - GoogleToolboxForMac/NSString+URLArguments (~> 2.1)
    - GTMOAuth2 (~> 1.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - GoogleToolboxForMac/DebugUtils (2.1.3):
    - GoogleToolboxForMac/Defines (= 2.1.3)
  - GoogleToolboxForMac/Defines (2.1.3)
  - GoogleToolboxForMac/NSData+zlib (2.1.3):
    - GoogleToolboxForMac/Defines (= 2.1.3)
  - GoogleToolboxForMac/NSDictionary+URLArguments (2.1.3):
    - GoogleToolboxForMac/DebugUtils (= 2.1.3)
    - GoogleToolboxForMac/Defines (= 2.1.3)
    - GoogleToolboxForMac/NSString+URLArguments (= 2.1.3)
  - GoogleToolboxForMac/NSString+URLArguments (2.1.3)
  - gRPC (1.8.0):
    - gRPC-RxLibrary (= 1.8.0)
    - gRPC/Main (= 1.8.0)
  - gRPC-Core (1.8.0):
    - gRPC-Core/Implementation (= 1.8.0)
    - gRPC-Core/Interface (= 1.8.0)
  - gRPC-Core/Implementation (1.8.0):
    - BoringSSL (~> 9.0)
    - gRPC-Core/Interface (= 1.8.0)
    - nanopb (~> 0.3)
  - gRPC-Core/Interface (1.8.0)
  - gRPC-ProtoRPC (1.8.0):
    - gRPC (= 1.8.0)
    - gRPC-RxLibrary (= 1.8.0)
    - Protobuf (~> 3.0)
  - gRPC-RxLibrary (1.8.0)
  - gRPC/Main (1.8.0):
    - gRPC-Core (= 1.8.0)
    - gRPC-RxLibrary (= 1.8.0)
  - GTMOAuth2 (1.1.6):
    - GTMSessionFetcher (~> 1.1)
  - GTMSessionFetcher (1.1.12):
    - GTMSessionFetcher/Full (= 1.1.12)
  - GTMSessionFetcher/Core (1.1.12)
  - GTMSessionFetcher/Full (1.1.12):
    - GTMSessionFetcher/Core (= 1.1.12)
  - ImageRow (3.0.0):
    - Eureka (~> 4.0)
  - leveldb-library (1.20)
  - nanopb (0.3.8):
    - nanopb/decode (= 0.3.8)
    - nanopb/encode (= 0.3.8)
  - nanopb/decode (0.3.8)
  - nanopb/encode (0.3.8)
  - Protobuf (3.5.0)
  - SDWebImage (4.2.2):
    - SDWebImage/Core (= 4.2.2)
  - SDWebImage/Core (4.2.2)
  - TwitterCore (3.1.0)
  - TwitterKit (3.3.0):
    - TwitterCore (>= 3.1.0)
  - ViewRow (0.2.0):
    - Eureka (>= 4.0.0)

DEPENDENCIES:
  - CDAlertView
  - Eureka
  - Firebase
  - FirebaseUI
  - ImageRow
  - ViewRow (from `https://github.com/EurekaCommunity/ViewRow`)

EXTERNAL SOURCES:
  ViewRow:
    :git: https://github.com/EurekaCommunity/ViewRow

CHECKOUT OPTIONS:
  ViewRow:
    :commit: f6518ba4224e33f168b89dc30b6d8ec3ba1a8c77
    :git: https://github.com/EurekaCommunity/ViewRow

SPEC CHECKSUMS:
  Bolts: ac6567323eac61e203f6a9763667d0f711be34c8
  BoringSSL: 84318770d120503ab1a6aaf1df777c5ca053697e
  CDAlertView: fdef4dbbdafd1481c18f5db64dac2d321f3b8cbb
  Eureka: c8bd5cc07143b6f66268c208d28a246c99b41955
  FBSDKCoreKit: 6f139173dc63a1deaff4430a55f2fe5bb222d2af
  FBSDKLoginKit: 56a057ca6822535ea0faa25f57a7c41edb697fd4
  Firebase: 710decbbc6d9d48530e9a5dba3209740c3532e05
  FirebaseAnalytics: 5b02a63ead2c3f0259cfc7f15e053e440587ecf8
  FirebaseAuth: dc0dd403beca5b2b016aac89c2d0b8dad1c81926
  FirebaseCore: 3c02ec652db3d03fdc8bc6d9154af3e20d64b6f5
  FirebaseDatabase: 7088bfc4af2cc00231bb36e1404fc2d7509eb4dc
  FirebaseFirestore: 0fb0301657759bdd7a4bc37a436e543a86b189ad
  FirebaseInstanceID: 81df5805a08001e69138664bdd02c6719a9ac80f
  FirebaseStorage: ab08d1c93a2feffa038fdd6693088b310ab1e6c6
  FirebaseUI: 883482fea73b73bbb488c55176f4c6ad128957eb
  GoogleSignIn: 3fdaa34a2ba04dbd7a25d7db39aecb0da98d5bdc
  GoogleToolboxForMac: 2501e2ad72a52eb3dfe7bd9aee7dad11b858bd20
  gRPC: cc3f797b97bf221a9e535e8e012a6f99b1d7f797
  gRPC-Core: 250fd60016c4e4c413279f4002679b0e14e7df26
  gRPC-ProtoRPC: 5b934b29a95b94b0f871d4fc361ff52269476765
  gRPC-RxLibrary: 7c57a1b2ff2f9cafb0face35bbfa0a326281295d
  GTMOAuth2: c77fe325e4acd453837e72d91e3b5f13116857b2
  GTMSessionFetcher: ebaa1f79a5366922c1735f1566901f50beba23b7
  ImageRow: 048123c296de9a6ac3998c415a6706c45ce480af
  leveldb-library: 08cba283675b7ed2d99629a4bc5fd052cd2bb6a5
  nanopb: 5601e6bca2dbf1ed831b519092ec110f66982ca3
  Protobuf: 8a9838fba8dae3389230e1b7f8c104aa32389c03
  SDWebImage: 89a9d32cd520bbb46eb14e541d5109b3564af198
  TwitterCore: 644d59e75abccb26cf0a9050d2c4dea0e5412241
  TwitterKit: a2e60ddcedbf54091eac6f27685ca7a87681e1d7
  ViewRow: 14475b337be9748b12a6df33d0a160bd5bd7765c

PODFILE CHECKSUM: 8236f48abbe049795e8faccf6bd77f77b1f74934

COCOAPODS: 1.3.1
