### ISSUE TITLE
Support One Time Code AutoFill on iOS 12

### ISSUE THREAD

**Issue by 0x7fs** [firebase/FirebaseUI-iOS#515] opened 2018-09-04 18:30 UTC
This ticket describes how to add support for allowing iOS 12 to autofill SMS 2FA codes into the text box in the phone verification view controller. This is similar to #384 which describes setting the field's [`textContentType`](https://developer.apple.com/documentation/uikit/uitextinputtraits/1649656-textcontenttype?language=objc) for types like username, password and phone number.

I believe the only change necessary to support this would be to update `FUICodeField` in the following ways:

1. Implement the `textContentType` property as part of the `UITextInputTraits` conformance.
    ```{objective-c}
    @property(nonatomic, copy) UITextContentType textContentType;
    ```
2. In `setUpFromNib`, set the `inputField`'s `textContentType` to `UITextContentTypeOneTimeCode` allowing it to autofill SMS codes.
    ```{objective-c}
    if (@available(iOS 12.0, *)) {
        _inputField.textContentType = UITextContentTypeOneTimeCode;
    }
    ```

Additional Information: https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_a_text_input_view?language=objc

**Comment by radvansky-tomas** [comment] 2018-11-19 05:06
What about email + password ? Cant we support auto-fill there ?

**Comment by alexsorokoletov** [comment] 2018-12-22 06:05
Wondering why FirebaseUI code will only enable that option if app deployment target is 12.1 or later.
My app has deployment target set to iOS 11 and when running on iOS 12 nothing happens.
Unless this was the intention, shouldn't that be replaced with the runtime check and not compilation time check?

**Comment by morganchen12** [comment] 2018-12-27 06:49
@alexsorokoletov sorry about that, that's a bug.

**Comment by morganchen12** [comment] 2019-01-31 21:59
#607

**Comment by ADevelopStudio** [comment] 2019-02-06 03:03
weird behaviour:
actually textContentType = .oneTimeCode works fine for most of the time and the problem is that because my project name has a digits in its name - iOS detects and pre-fills only this symbol.... 
so from, for example, "123123 is your verification code for Project4All" iOS grabs only "4" which is said

**Comment by naveengoyal1993** [comment] 2019-09-20 09:44
I am using the FirebaseUI for Phone Auth. OTP message does not fill the keyboard autofill suggestion box. OTP Code fill view (FUICodeField) does not appear the suggestion box in a keyboard. I have shared the screenshot link for this issue.
![firebase-auth](https://user-images.githubusercontent.com/32010174/65310443-f2beec80-dbab-11e9-8c40-54cb3bdc938e.PNG)

Please help me to resolve this issue.

Env:
Lib: Firebase (v6.8.1), FirebaseAuth (v6.2.3), FirebaseCore (v6.2.3) and FirebaseUI (v8.1.0). 
Deployment Target set to iOS 12.3.
iPhone 6 (v12.4.1).

**Comment by morganchen12** [comment] 2020-02-25 23:05
Closing this issue in favor of #775.

**Closed by morganchen12** 2020-02-25 23:05 UTC
Labels: auth
