### ISSUE TITLE
Ability to have sections in FirebaseTableViewDataSource

### ISSUE THREAD

**Issue by kermankohli** [firebase/FirebaseUI-iOS#8] opened 2015-09-12 20:51 UTC
It'd be really helpful if FirebaseTableViewDataSource.m allowed for UITableViewSections based on a specific variable. Basically something similar to NSFetchedResultsController used for Core Data :+1:

**Comment by mcdonamp** [comment] 2015-09-20 23:39
Yep, this would definitely be useful. I put some thought into this earlier, and my original thought was to use separate refs, so you would create a `FirebaseTableViewDataSource` and then add a section to it, and a section would contain a ref (or more likely a query). The approach mentioned above could allow for just a single ref, assuming you wanted to filter the data into sections based on the content of a single field.

This might fit in well for our eventual support for better client side filtering, so definitely on the roadmap after auth.

**Comment by kermankohli** [comment] 2015-10-03 01:40
@mcdonamp Alright, thanks for that! I'm not implementing Firebase right now but will be looking to move in about a month - do you reckon it'd be implemented by then?

**Comment by mcdonamp** [comment] 2015-10-03 01:42
Thanks to @pmodernme, it might be earlier: https://github.com/firebase/FirebaseUI-iOS/pull/13

**Comment by kermankohli** [comment] 2015-10-03 02:26
@mcdonamp looks pretty good, thanks @pmodernme!

**Comment by pmodernme** [comment] 2015-10-03 15:20
Happy to be of use!

**Comment by kermankohli** [comment] 2015-10-06 21:11
Hey guys just had a question,

If the refQuery was users/john/tasks (which contains the IDs of all the users), how would filtering/sorting work in that case?

**Comment by pmodernme** [comment] 2015-10-06 23:55
@kermankohli 
As my sectioning fork is currently...

If you don't set the predicate, or the sort descriptors (set them to nil), it will sort the snapshots alphabetically by key.

If you set the sortDescriptors (this is an array of `NSSortDescriptors`), it will sort first by the zeroth sort descriptor, then the first, and so on. The sort descriptor queries the snapshot. So you could do:

`@[[[NSSortDescriptor alloc] initWithKey:@"value.origin_date" ascending:NO]];`
This will order by the `origin_date` child of the snapshot, with the largest value at the top.

or

`@[[[NSSortDescriptor alloc] initWithKey:@"key" ascending:YES]];`
This will order by the `key` of the snapshot (the last key path of the ref).

You have to use a key path like `value.name` to query the value.


Predicates work much in the same way. You set the predicate to an NSPredicate.

`[NSPredicate predicateWithFormat:@"%K == %@", @"value.hidden", @NO];`

Only snapshots with the child `hidden` with a value of FALSE will be shown.

I hope that helps!

**Comment by kermankohli** [comment] 2015-10-07 00:42
@pmodernme 

Thanks for such a detailed write up! Just read back on what I wrote and I ended up confusing my self :-1: 

What I meant to say was if the refQuery was /users/john/tasks/ (which contains an array of tasks who's ids correspond to the task class) then how would sorting work, because the values themselves haven't been fetched.

Sorry for the confusion before!

**Comment by mcdonamp** [comment] 2015-10-07 00:49
What you're asking about is join functionality on top of the filtering, which we don't currently support. We're investigating something similar to what [Firebase-Util](https://github.com/firebase/firebase-util) offers in that respect, but, to be honest, doing all of that client side is really not something that we're interested in doing from a performance standpoint.

**Comment by kermankohli** [comment] 2015-10-07 00:55
Yeah it's kinda an edge case which might not be worth developing for. Would it be fine if I structured my data to look like /tasks/john/taskX rather /tasks/(tasks from /users/john/tasks/)?

**Comment by mcdonamp** [comment] 2015-10-07 01:15
It's a totally valid use case, it's just not something we support out of the box on the backend (being a NoSQL database). It's fine if you structure it that way, the issue is just that potentially pulling down all that task data and sorting it client side could be a pretty expensive operation.

Typically I recommend only pulling down the minimum amount of data required to sort/filter client side and then attach listeners on the relevant tasks/objects and grab those more full changes. Typically, for instance, you aren't filtering off the title or the description of the task (and those are relatively big), but you might be filtering off timestamps/tags, so keep the title/description in `tasks/$taskID` while putting other info in `users/john/tasks/$taskID` or similar.

**Comment by kermankohli** [comment] 2015-10-07 01:31
Right gotchya. In my case I need to sort/filter by 5 keys, so in that case I'll need to store all that information in users/john/tasks/$taskID?

**Comment by pmodernme** [comment] 2015-10-07 01:58
Ah! I have something similar in my own app. You have to sort or fetch by
something in the snapshot.
In mine, I have a list of subscriptions with basically just a timestamp,
Boolean, and an id for the data it relates too. The predicate is based on
the Boolean, and the sort is based on the timestamp. Then I use another ref
to populate the cell.

>

**Comment by kermankohli** [comment] 2015-10-07 04:49
That makes sense! Doesn't it lead to duplication of data though? Or is this normal when you denormalize data (I'm new to this haha)?

**Comment by mcdonamp** [comment] 2015-10-07 07:34
Yes, it can, though this is more normal in a NoSQL database--disk space is cheap, your time is not. It's effectively creating indices rather than relying on the DB to do so. Plus, with [multi-writes](https://www.firebase.com/blog/2015-09-24-atomic-writes-and-more.html) in Firebase, it's easy to keep these values in sync.

**Comment by mcdonamp** [comment] 2015-11-11 00:48
Closing because pull https://github.com/firebase/FirebaseUI-iOS/pull/13 deals with this

**Closed by mcdonamp** 2015-11-11 00:48 UTC
Labels: enhancement, help wanted

**Comment by cgossain** [comment] 2018-03-27 05:18
I've built an NSFetchedResultsController type solution for the Firebase Realtime Database, and I've just open sourced it. I've been using this in a few production apps for some time now.

https://github.com/cgossain/FirebaseResultsController

I'd love to hear your thoughts.
