### ISSUE TITLE
Custom authPickerViewController causes SIGABRT crash

### ISSUE THREAD

**Issue by ryandailey100** [firebase/FirebaseUI-iOS#290] opened 2017-06-02 16:13 UTC
I am trying to implement a custom UI for the authPickerViewController. Once this function get ran in the delegate, the app crashes:

func authPickerViewController(forAuthUI authUI: FUIAuth) -> FUIAuthPickerViewController {
        return CustomAuthPickerVC(authUI: authUI)
    }

**This is the crash details:**

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </var/mobile/Containers/Bundle/Application/610809A2-F7E3-45A1-BC96-AA5AFFAE4855/MyApp.app> (loaded)' with name 'FUICustomAuthPickerViewController''
*** First throw call stack:
(0x184bd8f5c 0x1997cff80 0x184bd8ea4 0x18a5d9990 0x18a492ce0 0x18a267e8c 0x18a12f23c 0x18a12f194 0x100230a58 0x100236720 0x100192064 0x100192234 0x10023668c 0x10014d7b4 0x10014cc08 0x10014cb98 0x10014cc58 0x10023e904 0x100150a58 0x1001511a0 0x18a1479f0 0x18a1b6fb0 0x18a1b6f4c 0x18a3d8930 0x18a3e4dc8 0x184b9048c 0x184b8fdc4 0x184b8dd28 0x184abcdc0 0x18fc10088 0x18a196f44 0x100180ef0 0x199ffa8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

Why does it crash? I have my project set up just like the example project.

**Comment by morganchen12** [comment] 2017-06-02 16:59
Closing as duplicate of #128. Try the workaround suggested there, and if it doesn't work, reopen this issue.

**Closed by morganchen12** 2017-06-02 16:59 UTC
