### ISSUE TITLE
FirebaseAuthUI unable to login with phone number

### ISSUE THREAD

**Issue by oligazar** [firebase/FirebaseUI-iOS#482] opened 2018-07-18 03:41 UTC
### Step 2: Describe your environment

  * Objective C or Swift: ____Swift
  * iOS version: _____10.0
  * Firebase SDK version: _____Using FirebaseCore (4.0.20)
  * FirebaseUI version: ____Using FirebaseAuth (4.6.1)
  * CocoaPods Version: ____1.5.0
  
### Step 3: Describe the problem:
I followed the [official tutorial ](https://firebase.google.com/docs/auth/ios/phone-auth) to implement authentication with phone.
At first I was getting "Something went wrong" dialog. Then I noticed "This fake notification should be forwarded to Firebase Auth." and "auth ui didSignInWith authDataResult, error: If app delegate swizzling is disabled, remote notifications received by UIApplicationDelegate need to be forwarded to FIRAuth's canHandleNotificaton: method." log messages, which was strange, since I didn't set FirebaseAppDelegateProxyEnabled flag to NO in Info.plist file.

My next step was trying to fix the log messages by adding 
` if Auth.auth().canHandleNotification(userInfo) {
            completionHandler(.noData)
            return
        }`
to `application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void)`
  
So I'm confused what I'm doing wrong? Why I was getting "This fake notification should be forwarded to Firebase Auth." log if I didn't set FirebaseAppDelegateProxyEnabled flag? Why verification stuck after forwarding notification to Firebase? 

#### Observed Results:

  After that the log errors gone, FirebaseUI forwarded me to page saying "Verifying you're not a robot.." showing only white screen afterwords saying "about:blanc". Clicking "Done" button results in "The interaction was cancelled by the user" 
  
#### Expected Results:

  Expected successful finishing of authentication process
  
#### Relevant Code:

  ```
  class AppDelegate: PlugableAppDelegate, FUIAuthDelegate {
    var window: UIWindow? = UIWindow()

    override init() {
        super.init()
        FirebaseApp.configure()
        let authUI = FUIAuth.defaultAuthUI()
        // You need to adopt a FUIAuthDelegate protocol to receive callback
        authUI?.delegate = self
    }
 // ... 
}

func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey : Any]? = nil) -> Bool {
        
        let authUI = FUIAuth.defaultAuthUI()
        
        let providers: [FUIAuthProvider] = [
            FUIGoogleAuth(),
            FUIFacebookAuth(),
            FUIPhoneAuth(authUI:FUIAuth.defaultAuthUI()!),
            ]
        authUI?.providers = providers
        
        return true
    }

 func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        
        if Auth.auth().canHandleNotification(userInfo) {
            completionHandler(.noData)
            return
        }
       // ...
}

 func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        Messaging.messaging().apnsToken = deviceToken
    }
  ```

**Comment by morganchen12** [comment] 2018-07-23 19:03
Are you running into the same error if you try to login via phone auth using one of the sample apps in this repo?

The page load that you dismissed was supposed to load a captcha to verify the user. After the captcha succeeds, the login SMS would be sent and the auth flow would continue.

**Comment by kumar-chalasani** [comment] 2018-08-02 15:48
I have the same situation - reCaptcha is shown, and after submitting the challenge to verify, it succeeds, but goes to about:blank.  and then the app crashes if i close the about:blank with Done.

according to the documentation, though, i should not even see a reCaptcha, though that's fine with me if it worked as it should (with login SMS code sent), but it doesnt right now.  

i have separately validated that i can receive APNs...via nodejs.  but even a test APN doesnt arrive from firebase console.

**Comment by kumar-chalasani** [comment] 2018-08-09 22:41
Hi MorganChen - I will try and send you a stack trace if I can get one.  I
have tried before but not been able to see any logs at all.   As for
whether The issue is reproducible from the build in GitHub,  I will try
that next week.

Thanks for your response.

**Comment by mohayoub** [comment] 2018-09-20 07:11
the same problem here .. any help :?

**Comment by markuswinkler** [comment] 2018-10-07 00:53
same here. Does this work for anyone?

**Comment by RJiryes** [comment] 2018-10-18 10:39
We have the same issue.. @markuswinkler, did you find a solution?

**Comment by Usman4Github** [comment] 2019-04-05 04:39
facing same error. do anyone got any solution

**Comment by SeanFromTheMatrix** [comment] 2019-04-12 06:45
no help so far

**Comment by morganchen12** [comment] 2019-04-12 18:30
Are any of you able to reproduce this with the sample app?

**Comment by JimmyJimmyJ** [comment] 2019-05-02 08:41
I got the same problem in my own app.
Funny is that it works on the Simulator for IPhone XS but no other Simulator.
I only noticed the problem when the Apple Team told me they cant login to verify my App for the App Store. Great.

I will try to reproduce it with the Sample App later when im home.

**Comment by JimmyJimmyJ** [comment] 2019-05-02 10:37
Unable to reproduce it. The Sample app works nice.

**Comment by JimmyJimmyJ** [comment] 2019-05-02 11:15
I hope someone can help me working this out.

Ive added:
`
    
    @available(iOS 9.0, *)
    func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any]) -> Bool {
        let sourceApplication = options[UIApplication.OpenURLOptionsKey.sourceApplication] as! String?
        return self.handleOpenUrl(url, sourceApplication: sourceApplication)
    }
    
    @available(iOS 8.0, *)
    func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
        return self.handleOpenUrl(url, sourceApplication: sourceApplication)
    }
    
    
    func handleOpenUrl(_ url: URL, sourceApplication: String?) -> Bool {
        if FUIAuth.defaultAuthUI()!.handleOpen(url, sourceApplication: sourceApplication) {
            return true
        }
        // other URL handling goes here.
        return false
    }`

To my AppDelegate and could see in the Debugger that

FUIAuth.defaultAuthUI()!.handleOpen(url, sourceApplication: sourceApplication)

returns false while url: URL "com.googleusercontent.apps.614093633313-3cev7tmsbqr27iku5l5ioebfeff6ijoc://firebaseauth/link?deep_link_id=https%3A%2F%2Ffeuerwehr-1.firebaseapp.com%2F__%2Fauth%2Fcallback%3FauthType%3DverifyApp%26recaptchaToken%3D03AOLTBLTT3JUXbory0YYjYiXckqKQSpC8-S6HEqZNqHRyRiYyMo_SR2oJDmKOgbwtTLgAO20yOgs6gb8TrTuo8adTRIWTricNtsIrKlTo_DmpHuW3LmwdM4zesHPIeNukxkDipeFVpfvVZ1mXwK9YfkNiFana_W2FVBB0Hu7xgz57zVxYw1y6__G5nMzzPWgxLeRIPPFY9ZyhYbS0DJV5ewZAdYJ-cVRLeRpseFHPTwaRSxdkj9ffiLCXY7it0puta9LOsCREzqEc4-7gDrZSWSwNxWpUoHXf2vbFhGhMbcqa7kNl-pt9O8skF3dW0b-mIExy-SsdSeCe9GRVHJZM6-ZbOMk2gqKWtg%26eventId%3Dyeytmvbmcs"
and sourceApplication:	String?	"com.apple.SafariViewService"


Any Ideas?

**Comment by JimmyJimmyJ** [comment] 2019-05-02 11:26
Meanwhile I tested it on a physical Device where I see the same Blank Screen.

**Comment by morganchen12** [comment] 2019-05-02 17:57
@renkelvin Any idea why `FUIAuth.defaultAuthUI()!.handleOpen(url, sourceApplication: sourceApplication)` would return false?

**Comment by JimmyJimmyJ** [comment] 2019-05-04 18:58
I'm done with this. After 2 Days without sleep because this problem kept me awake, I've switched my login method to anonymous and created my own phone number validation in Google Firestore.
It would be awesome if this gets fixed or if anyone knows a workaround. I really can't explain why it works in the Sample Project but not in mine.
But then again I started working with Swift about 9 Days ago, so it could still be a very stupid beginners mistake.

**Comment by renkelvin** [comment] 2019-05-17 01:06
I think this is a rare issue when background refresh is disabled. This pr should fix it: https://github.com/firebase/FirebaseUI-iOS/pull/681

**Comment by morganchen12** [comment] 2019-05-30 19:36
The fix has been released. If you're still running into this error, please open a new issue.

**Closed by morganchen12** 2019-05-30 19:36 UTC
Labels: auth

**Comment by RuchiraMore** [comment] 2019-07-02 12:03
I am getting issue on Firestore UI. 
I am presenting Firestore UI. But not able to interacting while using "Google Sign In".
