### ISSUE TITLE
Infinite loop of "enter phone number" screen

### ISSUE THREAD

**Issue by cyrilchandelier** [firebase/FirebaseUI-iOS#343] opened 2017-09-26 13:49 UTC
### Environment

  * Objective C or Swift: Swift 4
  * iOS version: 11
  * Firebase SDK version: 4.2.0
  * FirebaseUI version: 4.3.0 (also tried with 4.2.0)
  * CocoaPods Version: 1.4.0.beta.1
  
### Problem:

Infinite loop during phone authentication where the "enter phone number" screen is shown again (new screen) after tapping the "Verify" button, indefinitely.

Note that this was working before migration to Swift 4.

#### Steps to reproduce:

  1. Start phone authentication 
  2. Enter phone number
  3. Receive the SMS and copy it in the field
  4. Tap "Verify"
  
#### Observed Results:

  * The same screen is pushed onto the navigation controller, again and again
  * If I decide to enter the new code received (which is the same), and tap on "Verify", then it continues indefinitly
  
#### Expected Results:

  * After tapping on "Verify", I expect the method `authUI(authUI:user:error:)` to be called and the screen to be authentication screen to be dismiss
  
#### Relevant Code:

  ```
fileprivate lazy var uiAuth: FUIAuth = {
    guard let uiAuth = FUIAuth(uiWith: Auth.auth()) else {
        fatalError("Firebase auth is not available")
    }
    uiAuth.delegate = self
    
    return uiAuth
}()

fileprivate lazy var provider: FUIPhoneAuth = {
    let provider = FUIPhoneAuth(authUI: self.uiAuth)
    self.uiAuth.providers.append(provider)
    return provider
}()

func startLoginProcess() {
  // Prevent Firebase auth to dismiss my login gate
  let fakeViewController = UIViewController()
  fakeViewController.view.frame = viewController.view.bounds
  fakeViewController.view.backgroundColor = UIColor.clear
  viewController.view.addSubview(fakeViewController.view)

  provider.signIn(withPresenting: fakeViewController, phoneNumber: nil)
}
  ```

**Comment by cyrilchandelier** [comment] 2017-09-28 11:50
After more investigation on my end, it looks like it's not a Swift 4 issue, maybe an iOS 11 issue?

First step of the phone auth process is to show a "FUIPhoneEntryViewController" screen that is setting on the right side of the navigation bar a UIBarButtonItem using the "Verify" copy.
> https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebasePhoneAuthUI/FUIPhoneEntryViewController.m#L120

Then when clicking on this button, it seems to push a "FUIPhoneVerificationViewController" screen that is setting on the right side of the navigation bar a UIBarButtonItem using the "Next" copy.
> https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebasePhoneAuthUI/FUIPhoneVerificationViewController.m#L97

See attached screenshot:
![screen shot 2017-09-28 at 13 45 51](https://user-images.githubusercontent.com/820515/30964978-dc3068cc-a453-11e7-9b45-f8dfc2285694.png)

I'm on the "FUIPhoneVerificationViewController" screen but the button says "Verify", which ultimately seems to push another "FUIPhoneVerificationViewController instead of communication with the Firebase Auth API.

**Comment by yramanchuk** [comment] 2017-10-04 01:31
@cyrilchandelier I think the problem is in line: `viewController.view.addSubview(fakeViewController.view)`
`fakeViewController` was not added to viewController hierarchy (so it's not retained by anyone).

Please add that controller to the navigationController or present it from another controller.
You can try to use this method instead of `addSubview`:
`self.present(fakeViewController, animated: false, completion: nil)`
I assume mentioned code is executed inside currently visible `UIViewController` 

Please let me know if that helped you.

**Comment by yramanchuk** [comment] 2017-10-04 01:33
@cyrilchandelier Why you are creating new controller?
Why not just call:` provider.signIn(withPresenting: viewController, phoneNumber: nil)`

**Comment by cyrilchandelier** [comment] 2017-10-04 12:52
Creating a new view controller was a workaround to avoid my whole login module to be dismissed once the Phone Auth was completed, for some reason it was doing that.

Anyway, if there is no other person reporting this bug, it's probably coming from that, or something else in my setup; but I have no time to check it now that I've totally replace the FirebaseUI phone auth with a custom implementation.

Thanks for taking the time to read this issue, I'm closing now.

**Comment by Kcarter787** [comment] 2017-11-16 17:53
I had this issue only on iOS 11 as well. After a lot of digging I determined that the viewDidLoad in FUIPhoneVerificationViewController is sometimes not called
  
https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebasePhoneAuthUI/FUIPhoneVerificationViewController.m#L97

Because of this, the button text remained “Verify” and continued to call FUIPhoneEntryViewController’s “next" method. I suspect this was happening because my log in / log out functions weren't deallocating the onboarding flow memory properly. The issue was fixed after I added UIApplication.shared.keyWindow?.rootViewController = nil right before changing the root to the mainFeed on log in, and before setting the root back to onboarding on log out.

Given that the functionality of FUIPhoneVerificationViewController’s “next” button depends directly on the viewDidLoad being called every time it becomes the topViewController of the nav stack (because prior view controllers may have changed the right bar button item), perhaps code I linked above should be moved to viewWillAppear?

**Comment by morganchen12** [comment] 2017-11-16 18:26
@yramanchuk PTAL

**Comment by morganchen12** [comment] 2018-03-06 19:50
Closing this issue as it seems to have staled; if you have a project that reproduces this issue, please post it here and I'll reopen.

**Closed by morganchen12** 2018-03-06 19:50 UTC
Labels: question

**Comment by fedkis** [comment] 2018-08-17 09:45
I spent a lot of time because I encountered the bug in my project.
I just changed 
[self presentViewController:authViewController animated:YES completion:nil];
to
[self.view.window.rootViewController presentViewController:authViewController animated:YES completion:nil];

and the problem disapeared.
