### ISSUE TITLE
Fix travis error build

### ISSUE THREAD

**Issue by yramanchuk** [firebase/FirebaseUI-iOS#155] opened 2016-09-26 17:57 UTC
All travis builds are failing (in both branches: `master` and `0.5.6`)
https://travis-ci.org/firebase/FirebaseUI-iOS/builds

First error appeared after commit: https://github.com/firebase/FirebaseUI-iOS/commit/5a6bd83fb0024d4da971648d444551ade2519a98

I can see that later new/other errors were added on top of that one.

**Comment by morganchen12** [comment] 2016-09-26 18:23
duplicate of #145

**Comment by morganchen12** [comment] 2016-09-26 18:50
I made a commit that didn't touch our xcodeproj or source code at all and travis fixed itself 

l m a o

https://travis-ci.org/firebase/FirebaseUI-iOS/builds/162863736

**Comment by yramanchuk** [comment] 2016-09-26 19:05
Latest master build fails too https://travis-ci.org/firebase/FirebaseUI-iOS/builds/161772490

**Comment by morganchen12** [comment] 2016-09-26 19:35
we haven't merged v0.5.6 into master

**Comment by morganchen12** [comment] 2016-09-26 19:59
master is now passing https://travis-ci.org/firebase/FirebaseUI-iOS/builds/162880841

**Closed by morganchen12** 2016-09-26 19:59 UTC
Labels: bug
